apiVersion: v1
kind: Pod
metadata:
  name: influxdb-pod
  labels:
    app: ft_service
    tier: back-end
    name: influxdb-pod
spec:
  volumes:
  - name: influx-db
    hostPath:
      path: /mnt/influxdb/app
  containers:
  - name: influxdb
    image: influxdb_image
    ports:
    - containerPort: 8086
    volumeMounts:
    - name: influx-db
      mountPath: /var/lib/influxdb
    imagePullPolicy: Never
