apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: ft_service
    tier: back-end
    name: influxdb
spec:
  type: ClusterIP
  ports:
  - targetPort: 8086
    port: 8086
    protocol: TCP
  selector:
    app: ft_service
    tier: back-end
    name: influxdb
