apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: ft_service
    tier: back-end
    name: mysql-pod
spec:
  volumes:
  - name: mysql-db
    hostPath:
      path: /mnt/mysql/app
  containers:
  - name: mysql
    image: mysql_image
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-db
      mountPath: /app
    imagePullPolicy: Never
