apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ft_service
    tier: back-end
    name: mysql
spec:
  type: ClusterIP
  ports:
  - targetPort: 3306
    port: 3306
    protocol: TCP
  selector:
    app: ft_service
    tier: back-end
    name: mysql
