apiVersion: v1
kind: Pod
metadata:
  name: grafana-pod
  labels:
    app: ft_service
    tier: front-end
    name: grafana-pod
spec:
  volumes:
  - name: certifications
    hostPath:
      path: /certs
  containers:
  - name: grafana
    image: grafana_image
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: certifications
      mountPath: /certs
    imagePullPolicy: Never
