apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: ft_service
    tier: front-end
    name: grafana-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_service
      tier: front-end
      name: grafana-pod
  template:
    metadata:
      name: grafana-pod
      labels:
        app: ft_service
        tier: front-end
        name: grafana-pod
    spec:
      volumes:
      - name: certifications
        hostPath:
          path: /certs
      - name: grafana-persistent-storage
        persistentVolumeClaim:
          claimName: grafana-pv-claim
      containers:
      - name: grafana
        image: grafana_image
        ports:
        - name: https
          containerPort: 3000
        volumeMounts:
        - name: certifications
          mountPath: /certs
        - name: grafana-persistent-storage
          mountPath: /var/lib/grafana
        imagePullPolicy: Never
