apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: ft_service
    tier: front-end
    name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: MySharingKey
spec:
  type: LoadBalancer
  loadBalancerIP: MyClusterIP
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
  - name: https
    protocol: TCP
    targetPort: 443
    port: 443
  - name: ssh
    protocol: TCP
    targetPort: 22
    port: 22
  selector:
    app: ft_service
    tier: front-end
    name: nginx
