apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin-pod
  labels:
    app: ft_service
    tier: front-end
    name: phpmyadmin-pod
spec:
  volumes:
  - name: certifications
    hostPath:
      path: /certs
  containers:
  - name: phpmyadmin
    image: phpmyadmin_image
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: certifications
      mountPath: /certs
    imagePullPolicy: Never
