apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: ft_service
    tier: front-end
    name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_service
      tier: front-end
      name: phpmyadmin-pod
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: ft_service
        tier: front-end
        name: phpmyadmin-pod
    spec:
      volumes:
      - name: certifications
        hostPath:
          path: /certs
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: phpmyadmin
        image: phpmyadmin_image
        ports:
        - name: https
          containerPort: 5000
        volumeMounts:
        - name: certifications
          mountPath: /certs
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql	 
        imagePullPolicy: Never
