apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: ft_service
    tier: front-end
    name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: MySharingKey
spec:
  type: LoadBalancer
  loadBalancerIP: MyClusterIP
  ports:
  - name: https
    protocol: TCP
    targetPort: 5050
    port: 5050
  selector:
    app: ft_service
    tier: front-end
    name: wordpress
