apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels:
    app: ft_service
    tier: front-end
    name: wordpress-pod
spec:
  volumes:
  - name: certifications
    hostPath:
      path: /certs
  containers:
  - name: wordpress
    image: wordpress_image
    ports:
    - containerPort: 5050
    volumeMounts:
    - name: certifications
      mountPath: /certs
    imagePullPolicy: Never
