apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ft_service
    tier: front-end
    name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_service
      tier: front-end
      name: ftps-pod
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ft_service
        tier: front-end
        name: ftps-pod
    spec:
      volumes:
      - name: certifications
        hostPath:
          path: /certs
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: ftps
        image: ftps_image
        ports:
        - name: ftp21
          containerPort: 21
        - name: ftp20
          containerPort: 20
        - name: ftp30020
          containerPort: 30020
        - name: ftp30021
          containerPort: 30021
        volumeMounts:
        - name: certifications
          mountPath: /certs
        - name: ftps-persistent-storage
          mountPath: /home/__USER__
        imagePullPolicy: Never
