apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ft_service
    tier: front-end
    name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: MySharingKey
spec:
  type: LoadBalancer
  loadBalancerIP: MyClusterIP
  ports:
  - name: ftp21
    protocol: TCP  
    targetPort: 21
    port: 21
  selector:
    app: ft_service
    tier: front-end
    name: ftps-pod
