apiVersion: v1
kind: Pod
metadata:
  name: ftps-pod
  labels:
    app: ft_service
    tier: front-end
    name: ftps-pod
spec:
  volumes:
  - name: certifications
    hostPath:
      path: /certs
  - name: home
    hostPath:
      path: /mnt/ftps/home
  containers:
  - name: ftps
    image: ftps_image
    ports:
    - containerPort: 21
    volumeMounts:
    - name: certifications
      mountPath: /certs
    - name: home
      mountPath: /home/USER
    imagePullPolicy: Never
