apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ft_service
    tier: front-end
    name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: MySharingKey
spec:
  type: LoadBalancer
  loadBalancerIP: MyClusterIP
  ports:
  - name: ftp21
    protocol: TCP  
    targetPort: 21
    port: 21
  - name: ftp20
    protocol: TCP  
    targetPort: 20
    port: 20
  - name: ftp30020
    protocol: TCP  
    targetPort: 30020
    port: 30020
  - name: ftp30021
    protocol: TCP  
    targetPort: 30021
    port: 30021
  selector:
    app: ft_service
    tier: front-end
    name: ftps-pod
